# Generated by Django 4.2.23 on 2025-06-30 00:19

from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="country name"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="Optional ISO 3166-1 alpha-2 code",
                        max_length=3,
                        null=True,
                        verbose_name="country code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="destination name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="tours.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "ordering": ["country__name", "name"],
                "unique_together": {("country", "name")},
            },
        ),
        migrations.CreateModel(
            name="TourPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("VISA_FREE", "Visa Free"),
                            ("E_VISA", "E-Visa"),
                            ("ON_ARRIVAL", "On Arrival"),
                            ("STICKER_VISA", "Sticker Visa"),
                        ],
                        default="STICKER_VISA",
                        max_length=20,
                        verbose_name="visa type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in ETB or a common currency",
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="Short bullet points or key features, one per line.",
                        verbose_name="highlights",
                    ),
                ),
                (
                    "inclusions",
                    models.TextField(
                        blank=True,
                        help_text="What is included in the package, one per line.",
                        verbose_name="inclusions",
                    ),
                ),
                (
                    "exclusions",
                    models.TextField(
                        blank=True,
                        help_text="What is NOT included in the package, one per line.",
                        verbose_name="exclusions",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duration in days"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=tours.models.tour_package_image_path,
                        verbose_name="main image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this package currently available for booking?",
                        verbose_name="is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tour_packages",
                        to="tours.country",
                    ),
                ),
                (
                    "destinations",
                    models.ManyToManyField(
                        blank=True, related_name="tour_packages", to="tours.destination"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Package",
                "verbose_name_plural": "Tour Packages",
                "ordering": ["-created_at", "title"],
            },
        ),
    ]
